# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb8674d31e044a7207a03328d1257af05d4e58e18fb8caca4edefaad46035d1c9d85991cbf77c7ef89431ec1e03927770e478b1be3f50ff70624a887a73f1086

test:
  secret_key_base: 63b86ade7734865e0b98606d89ae052440fbbb0645a0493ae7547363de61fa540465e51cf700b17892fad45f0c7f26628be76967428c61037848fb478b0a2ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
